### ISSUE TITLE
error npm install

### ISSUE THREAD

**Issue by omgbox** [xat/hls-chromecast-demo#1]
root@nodejs-laptop:~/Downloads/hls-chromecast-demo# npm install
npm ERR! Failed to check out b7bf73d7bee06b3495156dcca714c80371346c75

error: index file ./objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small error: index file .git/objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small
npm ERR! Failed to check out b7bf73d7bee06b3495156dcca714c80371346c75

error: index file ./objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small error: index file .git/objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small
npm ERR! Failed to check out b7bf73d7bee06b3495156dcca714c80371346c75

error: index file ./objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small error: index file .git/objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small
npm ERR! Failed to check out b7bf73d7bee06b3495156dcca714c80371346c75

error: index file ./objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small error: pathspec '"b7bf73d7bee06b3495156dcca714c80371346c75\n\nerror: index file ./objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small"' did not match any file(s) known to git.
npm ERR! Failed to check out b7bf73d7bee06b3495156dcca714c80371346c75

error: index file ./objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small 
npm ERR! Linux 3.2.0-80-generic-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code 1

npm ERR! Command failed: git checkout b7bf73d7bee06b3495156dcca714c80371346c75
npm ERR! 
npm ERR! error: index file ./objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small
npm ERR! error: index file .git/objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small
npm ERR! error: index file .git/objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small
npm ERR! error: index file .git/objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small
npm ERR! error: pathspec '"b7bf73d7bee06b3495156dcca714c80371346c75\n\nerror: index file ./objects/pack/pack-6b579e3433e5b2aa8039ec3f2f6e82c6c60d5b1a.idx is too small"' did not match any file(s) known to git.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodejs/Downloads/hls-chromecast-demo/npm-debug.log
root@nodejs-laptop:~/Downloads/hls-chromecast-demo#

**Comment by xat** [comment]
hmm, can't reproduce this. seems like a git issue..
do you get the same error using `npm install hlscast -g`?

**Comment by omgbox** [comment]
yes , using npm install hlscast -g

 npm -v
1.4.28

node -v
v0.10.37

hlscast ./demo.mkv
launching player with input file: ./demo.mkv

/usr/lib/node_modules/hlscast/index.js:40
    if (meta.canPlay) {
            ^
TypeError: Cannot read property 'canPlay' of undefined
    at /usr/lib/node_modules/hlscast/index.js:40:13
    at /usr/lib/node_modules/hlscast/node_modules/chromecast-can-play/index.js:94:21
    at /usr/lib/node_modules/hlscast/node_modules/fluent-ffmpeg/lib/ffprobe.js:113:16
    at /usr/lib/node_modules/hlscast/node_modules/fluent-ffmpeg/lib/capabilities.js:194:9
    at /usr/lib/node_modules/hlscast/node_modules/fluent-ffmpeg/lib/capabilities.js:183:15
    at Object.cb [as oncomplete](fs.js:169:19)

**Comment by omgbox** [comment]
> ffmpeg -version
> ffmpeg version N-63893-gc69defd
> built on Oct 31 2014 05:16:04 with gcc 4.6 (Debian 4.6.3-1)
> configuration: --prefix=/root/ffmpeg-static/32bit --arch=x86_32 --extra-cflags='-m32 -I/root/ffmpeg-static/32bit/include -static' --extra-ldflags='-m32 -L/root/ffmpeg-static/32bit/lib -static' --extra-libs='-lxml2 -lexpat -lfreetype' --enable-static --disable-shared --disable-ffserver --disable-doc --enable-bzlib --enable-zlib --enable-postproc --enable-runtime-cpudetect --enable-libx264 --enable-gpl --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-gray --enable-libass --enable-libfreetype --enable-libopenjpeg --enable-libspeex --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-version3 --enable-libvpx
> libavutil      52. 89.100 / 52. 89.100
> libavcodec     55. 66.101 / 55. 66.101
> libavformat    55. 43.100 / 55. 43.100
> libavdevice    55. 13.101 / 55. 13.101
> libavfilter     4.  8.100 /  4.  8.100
> libswscale      2.  6.100 /  2.  6.100
> libswresample   0. 19.100 /  0. 19.100
> libpostproc    52.  3.100 / 52.  3.100

**Comment by AdelinoFilho** [comment]
Hello omgbox, I'm having the same problem.
You solve the problem? If so, you can share the solution?
Already, thanks!
